version: '2.0'
services:
  varnish:
    build: .docker/varnish
    ports:
    - "80:6081"
    - "6085:6085"
    environment:
      BACKENDS: "10.0.10.210"
      BACKENDS_PORT: "8080"
      BACKENDS_PROBE_INTERVAL: "3s"
      BACKENDS_PROBE_TIMEOUT: "1s"
      BACKENDS_PROBE_WINDOW: "3"
      BACKENDS_PROBE_THRESHOLD: "2"
      DASHBOARD_USER: "admin"
      DASHBOARD_PASSWORD: "admin"
      DASHBOARD_SERVERS: "varnish"
      DASHBOARD_DNS_ENABLED: "true"