version: '2.0'

services:
  varnish:
    image: eeacms/varnish:4.1-4.0
    ports:
      - "80:6081"
      - "6085:6085"
      - "6082:6082"
    volumes:
      - .docker/conf-varnish/drupal.vcl:/etc/varnish/conf.d/default.vcl
      - .docker/conf-varnish/secret:/etc/varnish/secret
    env_file:
      - docker.env

